import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@repo/ui';
import { theme } from '@/styles/theme';
import './globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

const RootLayout: React.FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return (
    <html lang={'en'}>
      <body className={inter.className}>
        <ThemeProvider themeConfig={theme}>{children}</ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
